language: java
jdk:
  - oraclejdk8

before_script:
 - git clone https://github.com/dirmeier/sgl4j.git
 - cd sgl4j && mvn install 

script: mvn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

